version: '3.8'

services:
  shell:
    build: .
    container_name: scr_shell
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - TERM=xterm-256color
    command: python3 shell.py

  shell-dev:
    build: .
    container_name: scr_shell_dev
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - TERM=xterm-256color
    command: bash
